import type { AnimationPreset, EffectDocumentV2, GroupElementDocument, PresetAnimationDocument, ShapeElementDocument, ShapeKind, Vec2 } from "./schema";
import { DEFAULT_TRANSFORM } from "./schema";

let serial = 0; const id = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${(++serial).toString(36)}`;
export function createShape(kind: ShapeKind, position: Vec2 = [0, 0], filled = false, durationMs = 700): ShapeElementDocument {
  const shapeId = id(kind); return { id: shapeId, type: "shape", name: kind[0]!.toUpperCase() + kind.slice(1), visible: true, locked: false, timing: { startMs: 0, durationMs }, transform: { ...DEFAULT_TRANSFORM, position, size: kind === "rectangle" ? [96, 58] : kind === "line" ? [100, 4] : [64, 64] }, opacity: 1, animations: [], shape: { kind, sides: kind === "hexagon" ? 6 : 5, points: 5, innerRatio: .45 }, appearance: { fill: { enabled: filled, color: "#f8fafc" }, stroke: { enabled: !filled, color: "#8bd97b", width: 3 }, opacity: 1, blendMode: "normal" } };
}
export function createAnimation(preset: AnimationPreset, durationMs = 350): PresetAnimationDocument { return { id: id("anim"), type: "preset", preset, name: preset.replace(/([A-Z])/g, " $1").replace(/^./, (c) => c.toUpperCase()), enabled: true, timing: { startMs: 0, durationMs }, easing: "easeOutCubic", params: {} }; }
export function createBlankMotionEffect(name = "Novo efeito", target: EffectDocumentV2["target"] = "click"): EffectDocumentV2 { const shape = createShape("circle", [0, 0], false, target === "halo" ? 1600 : 700); shape.name = target === "halo" ? "Anel do halo" : "Círculo"; shape.transform.size = target === "halo" ? [92, 92] : shape.transform.size; shape.animations = target === "halo" ? [createAnimation("pulse", 1600), createAnimation("spin", 1600)] : [createAnimation("scaleOut", 700), createAnimation("fadeOut", 350)]; if (target === "click") shape.animations[1]!.timing.startMs = 350; return { schemaVersion: 2, target, id: `effect-${Date.now().toString(36)}`, metadata: { name, description: target === "halo" ? "Halo contínuo criado no RadiantCursor Studio" : "Composição geométrica criada no RadiantCursor Studio", author: "", tags: [] }, durationMs: target === "halo" ? 1600 : 700, rootIds: [shape.id], elements: { [shape.id]: shape } }; }
function burstEffect(): EffectDocumentV2 {
  const document = createBlankMotionEffect("Explosão estelar"); document.id = "builtin-star-burst"; document.metadata = { name: "Explosão estelar", description: "Composição de estrelas, losangos e ondas", author: "RadiantCursor", tags: ["built-in"] }; document.durationMs = 850; document.rootIds = []; document.elements = {};
  const groupId = "burst-group", groupRotate = createAnimation("rotate", 850); groupRotate.params.turns = .18; const group: GroupElementDocument = { id: groupId, type: "group", name: "Explosão", visible: true, locked: false, timing: { startMs: 0, durationMs: 850 }, transform: { ...DEFAULT_TRANSFORM, size: [1, 1] }, opacity: 1, animations: [groupRotate], children: [] }; document.elements[groupId] = group; document.rootIds.push(groupId);
  for (let i = 0; i < 8; i++) { const a = i * Math.PI / 4, shape = createShape(i % 2 ? "diamond" : "star", [Math.cos(a) * 38, Math.sin(a) * 38], true, 700); shape.id = `burst-shape-${i}`; shape.name = `Fragmento ${i + 1}`; shape.transform.size = i % 2 ? [13, 13] : [18, 18]; shape.appearance.fill.color = i % 2 ? "#b4eaa8" : "#ffffff"; const move = createAnimation("moveAway", 620), spin = createAnimation("spin", 700), fade = createAnimation("fadeOut", 300); move.params.distance = 75; spin.params.turns = i % 2 ? 1 : -.7; fade.timing.startMs = 400; shape.animations = [move, spin, fade]; document.elements[shape.id] = shape; group.children.push(shape.id); }
  const ring = createShape("circle", [0, 0], false, 650); ring.id = "burst-ring"; ring.name = "Onda central"; ring.transform.size = [42, 42]; const grow = createAnimation("scale", 650), fade = createAnimation("fadeOut", 300); grow.params.amount = 3.2; fade.timing.startMs = 350; ring.animations = [grow, fade]; document.elements[ring.id] = ring; group.children.unshift(ring.id); return document;
}
export const MOTION_BUILTINS: EffectDocumentV2[] = [burstEffect(), (() => { const d = createBlankMotionEffect("Pulso minimalista"); d.id = "builtin-minimal-pulse"; d.metadata.tags = ["built-in"]; return d; })(), (() => { const d = createBlankMotionEffect("Halo orbital", "halo"); d.id = "builtin-orbital-halo"; d.metadata.tags = ["built-in", "halo"]; return d; })()];
export function cloneMotionEffect(value: EffectDocumentV2): EffectDocumentV2 { return structuredClone(value); }
